[workspace]

members = [
    "envoy-sdk",
    "examples/access-logger",
    "examples/access-logger/wasm/module",
    "examples/http-filter",
    "examples/http-filter/wasm/module",
    "examples/network-filter",
    "examples/network-filter/wasm/module",
]
