[workspace]

members = [
    "envoy-sdk",
    "examples/access-logger",
    "examples/http-filter",
    "examples/network-filter",
    "support/envoy-abi-stubs",
    "support/extension-abi-memory",
]
