[package]
name = "envoy-sdk"
version = "0.0.0"
authors = ["Tetrate Labs <tetratelabs@tetrate.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proxy-wasm = { path = "/Users/yaro/ws/envoy/src/github.com/proxy-wasm/proxy-wasm-rust-sdk" }

[dev-dependencies]
envoy-abi-stubs = { path = "../support/envoy-abi-stubs" }
